appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: S1iLxWAWBUd9w0j8o3wZb3AKuhuzJwLTKy3oTCvJkHtCnk75LgUJC6bAA/asg/VIhlp/ayrQzmRZMoMpnqSM+K7OWPXLe31heZWTiWoLaCLXrHhTC7XgVxp0Wb3k5A3emgrMxfpTLbrtCSyZsdZ5hKoCec35Tzyjgd6KfCEKkHgnpCvWO1NZ6u/CsLmdGqJpu81YOJzexv3ICWvdXNOmKIzqRkhhIpVOH203eHC891Fn78XRTn3EwGJtVsNMlNxr0g5ZkE+pnTW2KcuquAluxJp5grGN+OjzsfTICcRJlH7vzLsxYxaVp2WjRkiAIyXz/Zo/ubQBCvhXoqG7B7Fc0LQyFjIlKOxN3nfj8k1eozVqbMp1X7QTAYV4aXeEQDHT+iXirObm8fb4aGveNHMj3eAd/nf4VWXx0Rjls4lRa7ZKNaRoHR1d1T8gdKA/A5Xh7t2E+O9LELJgRsXht0aXc+Uq0KsH7s9A+fqLTfY6wdVLktWCehVbwrMPQZfIsjApb1oMzu7rjCteZ4ISglcFuVo4bQKmpxNHo39dOtMUicFRejYZ5aLap/84EywavWEmYrHGylooJ/3768ZWe9TeOfRljpN9WlD+zkXNmDUn8TWarBL+c+59Q6WU4zmKB2jvL5GgIGLgSuKMyncYY6FTq3k1R1wvhgUSfU2i3rnlP9U=}
